version: '3.3'

services:
  ##############################################################
  # DB Mysql
  ##############################################################
  database:
    image: mysql:5.7.21
    container_name: mysql_hc_tracking
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=1
      --innodb_use_native_aio=0
      # --innodb_force_recovery=1
      # --init-file ./initdata/init_mysql_tracking_server.sql
    restart: always
    environment:
      MYSQL_DATABASE: hc_tracking
      MYSQL_USER: hc_tracking
      MYSQL_PASSWORD: hc_tracking1!@
      MYSQL_ROOT_PASSWORD: root1!@
      TZ: Asia/Seoul
    volumes:
      - ${MYSQL_DATA_FOLDER}:/var/lib/mysql             # windows volumes link
      - ./initdata/:/docker-entrypoint-initdb.d
      #- /var/lib/mysql:/var/lib/mysql  # 리눅스용 DATA 볼륨
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    ports:
    - 3306:3306
  ##############################################################
  # DB Web Manager
  ##############################################################
  adminer:
    image: adminer
    container_name: adminer_hc_tracking
    restart: always
    ports:
    - 8080:8080


  ##############################################################
  # No Sql DB Cassandra
  ##############################################################
  cassandra:
    build: ./cassandra
    container_name: cassandra_hc_tracking
    restart: always
    environment:
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_BROADCAST_ADDRESS: 1.2.3.4
      #CASSANDRA_LISTEN_ADDRESS: localhost
      #CASSANDRA_SEEDS: 127.0.0.1
    #volumes:
      #- ${CASSANDRA_DATA_FOLDER}:/var/lib/cassandra
      #- ./cassandra/data/:/docker-entrypoint-initdb.d
      #- ${CASSANDRA_DATA_FOLDER}/config:/etc/cassandra/                # configration files
    ports:
      #- 7000:7000
      #- 7001:7001
      #- 7199:7199
      - 9042:9042
      #- 9160:9160

# Dockerfile 컨테이너 안의 내부 경로( virtual machine 안에 볼륨 링크)
#volumes:
#  db-mysql-data:


